### ISSUE TITLE
Add-ARPEntries does not add `-` on first ARP entry

### ISSUE THREAD

**Issue by russellbanks** [jedieaston/Add-ARPEntries#1]
### Bug Description

The output does not have a `-` on the first ARP entry

#### Actual Result:

```yaml
  AppsAndFeaturesEntries:
    DisplayName: [Name of application]
    ProductCode: [Product code]
```

#### Expected Result:

```yaml
  AppsAndFeaturesEntries:
  - DisplayName: [Name of application]
    ProductCode: [Product code]
```
