### ISSUE TITLE
Blank ARP Entries should not be included

### ISSUE THREAD

**Issue by russellbanks** [jedieaston/Add-ARPEntries#12]
### Bug description

Blank ARP Entries are included in the output of Add-ARPEntries.ps1 but should not be included at all.

#### Current behaviour
```yaml
AppsAndFeaturesEntries:
- DisplayName: Package1
  DisplayVersion:
  Publisher:
```

#### Expected behaviour:
```yaml
AppsAndFeaturesEntries:
- DisplayName: Package1
```
