### ISSUE TITLE
Only add ARP values if they do not match metadata values

### ISSUE THREAD

**Issue by russellbanks** [jedieaston/Add-ARPEntries#2]
For example, running the script on Python 3.8.5 generates these values:

```yaml
  AppsAndFeaturesEntries:
  - DisplayName: Python 3.8.5 (64-bit)
    Publisher: Python Software Foundation
    DisplayVersion: 3.8.5150.0
    ProductCode: '{de694e50-e0d0-48a5-9a7a-56fd037154e2}'
```

In this case, the `Publisher` and the `DisplayVersion` match the current metadata values and would be asked to be removed by the moderators, removing the ease of automation you could get from recursively running the script.

I'm not sure how difficult this would be to implement but ideally the script could identify that the those values match the current metadata and wouldn't add those, so that you'd end up with a result more like this:

```yaml
  AppsAndFeaturesEntries:
  - DisplayName: Python 3.8.5 (64-bit)
    ProductCode: '{de694e50-e0d0-48a5-9a7a-56fd037154e2}'
```

See https://github.com/microsoft/winget-pkgs/pull/65795#issue-1301190831

**Comment by jedieaston** [comment]
This should've been resolved by https://github.com/jedieaston/Add-ARPEntries/commit/d5e2001dccc435fd3921ae014459fa80f09134eb, can you take a look and see if that's what you want?

**Comment by russellbanks** [comment]
Working great, for the most part, but in my test PR (https://github.com/microsoft/winget-pkgs/pull/70461), there were a few entries where the publisher was left blank

**Comment by jedieaston** [comment]
It looks like the Edge updater was running at the same time as the installer in the container (I don't think Zwift installs the Microsoft Edge Updater :D). Can you try rebuilding the docker container (in the root of the project run `docker build . -t wingettest`) and doing that one again? The Dockerfile installs the latest version of Edge to try to prevent that from happening (and that works 99% of the time).

(The publisher being blank is a different problem unrelated to this. powershell-yaml serializes properties even if they are empty. I need to just remove empty properties before serializing.)

**Comment by russellbanks** [comment]
Attempt 2 with a rebuit docker container:
```yaml
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft Edge Update
    DisplayVersion: 1.3.135.41
    Publisher: 
    ProductCode: Microsoft Edge Update
  - DisplayName: Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.29.30139
    DisplayVersion: 14.29.30139.0
    Publisher: Microsoft Corporation
    ProductCode: '{2c673fb6-3e65-4751-965d-33d30b68a8a6}'
  - DisplayName: Microsoft Edge Update
    DisplayVersion: 1.3.165.21
    Publisher: 
    ProductCode: Microsoft Edge Update
  - DisplayName: Microsoft Edge WebView2 Runtime
    DisplayVersion: 104.0.1293.54
    Publisher: Microsoft Corporation
    ProductCode: Microsoft EdgeWebView
  - DisplayName: Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.31.31103
    DisplayVersion: 14.31.31103.0
    Publisher: Microsoft Corporation
    ProductCode: '{2aaf1df0-eb13-4099-9992-962bb4e596d1}'
  - DisplayName: Zwift version 1.1.4
    ProductCode: '{E4DA422A-82AB-44A4-B3A5-0AF60F47B7AB}_is1'
```
It's less entries than last time but still more than Zwift
