### ISSUE TITLE
InstallerType is always re-added under each installer

### ISSUE THREAD

**Issue by russellbanks** [jedieaston/Add-ARPEntries#4]
It is common that there will be two installers in a manifest, for example, an x64 and x86 version. These would likely have the same installer type, so this would be at the top of the file to prevent redundancy:

```yaml
# yaml-language-server: $schema
PackageIdentifier:
PackageVersion:
MinimumOSVersion: 10.0.0.0
InstallerType: inno
...
```
When running this script, it will unnecessarily add the InstallerType again for each installer, resulting in potentially three repeated references to the same InstallerType, that then have to be removed:
```yaml
...
- Architecture: x64
  InstallerUrl:
  InstallerSha256:
  InstallerType: inno
...
- Architecture: x86
  InstallerUrl:
  InstallerSha256:
  InstallerType: inno
...
```
