### ISSUE TITLE
Put ARP entries at top of manifest if multiple installers match

### ISSUE THREAD

**Issue by russellbanks** [jedieaston/Add-ARPEntries#5]
If there is only one installer, or multiple installers have the same ARP entries (assuming those multiple installers are exe files and don't contain an msi), the ARP entries can go at the top of the manifest rather than under each installer:
```yaml
...
UpgradeBehavior:
AppsAndFeaturesEntries:
- DisplayName: FreeTube 0.13.2
  ProductCode: 609c326f-6a5e-5cd1-9fc0-6e966fad073f
...
```
If you were to run a yamlcreate update on this afterwards, it would remove those entries under each installer and place it at the top of the file like so, to reduce redundancy.

**Comment by russellbanks** [comment]
A good example of this is StandardNotes:

```yaml
AppsAndFeaturesEntries:
- DisplayName: Standard Notes 3.23.119
  ProductCode: 774f2290-3906-58eb-baae-35b0dc01c31e
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/standardnotes/app/releases/download/%40standardnotes%2Fdesktop%403.23.119/standard-notes-3.23.119-win-x64.exe
  InstallerSha256: 1E8D4A9CB0B97E1C87E61907B33CF5E1A67C6E3414C515CCF4AFC2F10726DC5D
- Architecture: x86
  InstallerUrl: https://github.com/standardnotes/app/releases/download/%40standardnotes%2Fdesktop%403.23.119/standard-notes-3.23.119-win-ia32.exe
  InstallerSha256: 393C5D00168CAD76E4CE7D60E3097B3901018846EEDC3ADE68BDE41E800FF21D
- Architecture: neutral
  InstallerUrl: https://github.com/standardnotes/app/releases/download/%40standardnotes%2Fdesktop%403.23.119/standard-notes-3.23.119-win.exe
  InstallerSha256: 605F96D004A46DE2C133C02EBE0016DB2CC25DAEBBBF3D74234E4573C56A3E24
```
Because all those installers have the same ARP Entries, the entries are placed above the installers, as to not repeat the same information three times.
